name: 'Hello World'
description: 'Run an apply pattern'
inputs:
  pattern: 
    description: 'Pattern To run'
    required: true
  testFile: 
    description: 'File to apply pattern to'
    required: true
runs:
  using: 'composite'
  steps:
    - name: install grit
      shell: bash
      id: download
      run: |
        curl -fsSL https://docs.grit.io/install | bash
    - name: init grit
      id: init
      shell: bash
      run: |
        grit init
    - name: run grit check
      id: check
      shell: bash
      run: |
        grit apply ${{ inputs.pattern }} ${{ inputs.testfile }}
